info:
  contact:
    email: hyunho129@naver.com
    name: Hyeonho Park
    url: https://github.com/HyeonHo-Park/LINE
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Swagger TEST API
  version: "1.0"
paths: {}
swagger: "2.0"
